export default {
    // button_0_0: {
    //     default: require("../../assets/image2/default/default1_0.png"),
    //     ppt: require("../../assets/image2/ppt/1-1.png"),
    //     question: require("../../assets/image2/question/1-1.png"),
    //     question_pressed: require("../../assets/image2/question/1-2.png"),
    //     word: require("../../assets/image2/word/1-1.png"),
    //     resourceWeb: require("../../assets/image2/resourceWeb/1-1.png"),
    //     videoAndSound: require("../../assets/image2/videoAndSound/1-1.png"),
    // },
    // button_0_1: {
    //     default: require("../../assets/image2/default/default6_0.png"),
    //     ppt: require("../../assets/image2/ppt/6-1.png"),
    //     ppt_pressed: require("../../assets/image2/ppt/6-2.png"),
    //     question: require("../../assets/image2/question/6-0.png"),
    //     word: require("../../assets/image2/word/6-1.png"),
    //     resourceWeb: require("../../assets/image2/resourceWeb/6-0.png"),
    //     videoAndSound: require("../../assets/image2/videoAndSound/6-0.png"),
    // },
    // button_0_2: {
    //     default: require("../../assets/image2/default/default4_0.png"),
    //     ppt: require("../../assets/image2/ppt/4-0.png"),
    //     question: require("../../assets/image2/question/4-1.png"),
    //     question_pressed: require("../../assets/image2/question/4-2.png"),
    //     word: require("../../assets/image2/word/4-1.png"),
    //     resourceWeb: require("../../assets/image2/resourceWeb/4-0.png"),
    //     videoAndSound: require("../../assets/image2/videoAndSound/4-1.png"),
    // },
    // button_1_0: {
    //     default: require("../../assets/image2/default/default2_0.png"),
    //     ppt: require("../../assets/image2/ppt/2-1.png"),
    //     question: require("../../assets/image2/question/2-1.png"),
    //     question_pressed: require("../../assets/image2/question/2-2.png"),
    //     word: require("../../assets/image2/word/2-1.png"),
    //     resourceWeb: require("../../assets/image2/resourceWeb/2-1.png"),
    //     videoAndSound: require("../../assets/image2/videoAndSound/2-1.png"),
    // },
    // button_1_1: {
    //     default: require("../../assets/image2/default/default7_0.png"),
    //     ppt: require("../../assets/image2/ppt/7-1.png"),
    //     ppt_pressed: require("../../assets/image2/ppt/7-1.png"),
    //     question: require("../../assets/image2/question/7-0.png"),
    //     word: require("../../assets/image2/word/7-1.png"),
    //     word_pressed: require("../../assets/image2/word/7-2.png"),
    //     resourceWeb: require("../../assets/image2/resourceWeb/7-0.png"),
    //     videoAndSound: require("../../assets/image2/videoAndSound/7-1.png"),
    //     videoAndSound_pressed: require("../../assets/image2/videoAndSound/7-2.png"),
    // },
    // button_1_2: {
    //     default: require("../../assets/image2/default/default8_0.png"),
    //     ppt_openPPT: require("../../assets/image2/ppt/8-1.png"),
    //     ppt_playPPT: require("../../assets/image2/ppt/8-2.png"),
    //     question_openQuestion: require("../../assets/image2/question/8-1.png"),
    //     question_showQuestionAnswer: require("../../assets/image2/question/8-2.png"),
    //     word: require("../../assets/image2/word/8-0.png"),
    //     resourceWeb: require("../../assets/image2/resourceWeb/8-0.png"),
    //     videoAndSound: require("../../assets/image2/videoAndSound/8-1.png"),
    // },
    // button_1_3: {
    //     default: require("../../assets/image2/default/default9_0.png"),
    //     ppt: require("../../assets/image2/ppt/9-1.png"),
    //     ppt_pressed: require("../../assets/image2/ppt/9-2.png"),
    //     question: require("../../assets/image2/question/9-0.png"),
    //     word: require("../../assets/image2/word/9-1.png"),
    //     word_pressed: require("../../assets/image2/word/9-2.png"),
    //     resourceWeb: require("../../assets/image2/resourceWeb/9-0.png"),
    //     videoAndSound: require("../../assets/image2/videoAndSound/9-1.png"),
    //     videoAndSound_pressed: require("../../assets/image2/videoAndSound/9-2.png"),
    // },
    // button_2_0: {
    //     default: require("../../assets/image2/default/default3_0.png"),
    //     ppt: require("../../assets/image2/ppt/3-1.png"),
    //     question: require("../../assets/image2/question/3-0.png"),
    //     word: require("../../assets/image2/word/3-1.png"),
    //     resourceWeb: require("../../assets/image2/resourceWeb/3-1.png"),
    //     videoAndSound: require("../../assets/image2/videoAndSound/3-1.png"),
    // },
    // button_2_1: {
    //     default: require("../../assets/image2/default/default10_0.png"),
    //     ppt: require("../../assets/image2/ppt/10-1.png"),
    //     ppt_pressed: require("../../assets/image2/ppt/10-2.png"),
    //     question: require("../../assets/image2/question/10-0.png"),
    //     word: require("../../assets/image2/word/10-1.png"),
    //     resourceWeb: require("../../assets/image2/resourceWeb/10-0.png"),
    //     videoAndSound: require("../../assets/image2/videoAndSound/10-0.png"),
    // },
    // button_2_2: {
    //     default: require("../../assets/image2/default/default5_0.png"),
    //     ppt: require("../../assets/image2/ppt/5-0.png"),
    //     question: require("../../assets/image2/question/5-1.png"),
    //     question_pressed: require("../../assets/image2/question/5-2.png"),
    //     word: require("../../assets/image2/word/5-1.png"),
    //     resourceWeb: require("../../assets/image2/resourceWeb/5-0.png"),
    //     videoAndSound: require("../../assets/image2/videoAndSound/5-1.png"),
    // },
    default: {
        png0: [0, require("../../../assets/image2/default/default1_0.png")],
        png1: [0, require("../../../assets/image2/default/default6_0.png")],
        png2: [0, require("../../../assets/image2/default/default4_0.png")],
        png3: [0, require("../../../assets/image2/default/default2_0.png")],
        png4: [0, require("../../../assets/image2/default/default7_0.png")],
        png5: [0, require("../../../assets/image2/default/default8_0.png")],
        png6: [0, require("../../../assets/image2/default/default9_0.png")],
        png7: [0, require("../../../assets/image2/default/default3_0.png")],
        png8: [0, require("../../../assets/image2/default/default10_0.png")],
        png9: [0, require("../../../assets/image2/default/default5_0.png")],
    },
    openQuestion: {
        png0: [1, require("../../../assets/image2/question/1-1.png")],
        png1: [0, require("../../../assets/image2/question/6-0.png")],
        png2: [1, require("../../../assets/image2/question/4-1.png")],
        png3: [1, require("../../../assets/image2/question/2-1.png")],
        png4: [0, require("../../../assets/image2/question/7-0.png")],
        png5: [1, require("../../../assets/image2/question/8-1.png")],
        png6: [0, require("../../../assets/image2/question/9-0.png")],
        png7: [1, require("../../../assets/image2/question/3-1.png")],
        png8: [0, require("../../../assets/image2/question/10-0.png")],
        png9: [1, require("../../../assets/image2/question/5-1.png")],
    },
    showQuestionAnswer: {
        png0: [1, require("../../../assets/image2/question/1-1.png")],
        png1: [0, require("../../../assets/image2/question/6-0.png")],
        png2: [1, require("../../../assets/image2/question/4-1.png")],
        png3: [1, require("../../../assets/image2/question/2-1.png")],
        png4: [0, require("../../../assets/image2/question/7-0.png")],
        png5: [1, require("../../../assets/image2/question/8-2.png")],
        png6: [0, require("../../../assets/image2/question/9-0.png")],
        png7: [1, require("../../../assets/image2/question/3-1.png")],
        png8: [0, require("../../../assets/image2/question/10-0.png")],
        png9: [1, require("../../../assets/image2/question/5-1.png")],
    },
    openPPT: {
        png0: [1, require("../../../assets/image2/ppt/1-1.png")],
        png1: [1, require("../../../assets/image2/ppt/6-1.png")],
        png2: [0, require("../../../assets/image2/ppt/4-0.png")],
        png3: [1, require("../../../assets/image2/ppt/2-1.png")],
        png4: [0, require("../../../assets/image2/ppt/7-0.png")],
        png5: [1, require("../../../assets/image2/ppt/8-1.png")],
        png6: [0, require("../../../assets/image2/ppt/9-0.png")],
        png7: [1, require("../../../assets/image2/ppt/3-1.png")],
        png8: [1, require("../../../assets/image2/ppt/10-1.png")],
        png9: [0, require("../../../assets/image2/ppt/5-0.png")],
    },
    playPPT: {
        png0: [1, require("../../../assets/image2/ppt/1-1.png")],
        png1: [1, require("../../../assets/image2/ppt/6-1.png")],
        png2: [0, require("../../../assets/image2/ppt/4-0.png")],
        png3: [1, require("../../../assets/image2/ppt/2-1.png")],
        png4: [1, require("../../../assets/image2/ppt/7-1.png")],
        png5: [1, require("../../../assets/image2/ppt/8-2.png")],
        png6: [1, require("../../../assets/image2/ppt/9-1.png")],
        png7: [1, require("../../../assets/image2/ppt/3-1.png")],
        png8: [1, require("../../../assets/image2/ppt/10-1.png")],
        png9: [0, require("../../../assets/image2/ppt/5-0.png")],
    },
    openWord: {
        png0: [1, require("../../../assets/image2/word/1-1.png")],
        png1: [1, require("../../../assets/image2/word/6-1.png")],
        png2: [1, require("../../../assets/image2/word/4-1.png")],
        png3: [1, require("../../../assets/image2/word/2-1.png")],
        png4: [1, require("../../../assets/image2/word/7-1.png")],
        png5: [0, require("../../../assets/image2/word/8-0.png")],
        png6: [1, require("../../../assets/image2/word/9-1.png")],
        png7: [1, require("../../../assets/image2/word/3-1.png")],
        png8: [1, require("../../../assets/image2/word/10-1.png")],
        png9: [0, require("../../../assets/image2/word/5-0.png")],
    },
    openResourceWeb: {
        png0: [1, require("../../../assets/image2/resourceWeb/1-1.png")],
        png1: [0, require("../../../assets/image2/resourceWeb/6-0.png")],
        png2: [0, require("../../../assets/image2/resourceWeb/4-0.png")],
        png3: [1, require("../../../assets/image2/resourceWeb/2-1.png")],
        png4: [0, require("../../../assets/image2/resourceWeb/7-0.png")],
        png5: [0, require("../../../assets/image2/resourceWeb/8-0.png")],
        png6: [0, require("../../../assets/image2/resourceWeb/9-0.png")],
        png7: [1, require("../../../assets/image2/resourceWeb/3-1.png")],
        png8: [0, require("../../../assets/image2/resourceWeb/10-0.png")],
        png9: [0, require("../../../assets/image2/resourceWeb/5-0.png")],
    },
    play: {
        png0: [1, require("../../../assets/image2/videoAndSound/1-1.png")],
        png1: [0, require("../../../assets/image2/videoAndSound/6-0.png")],
        png2: [1, require("../../../assets/image2/videoAndSound/4-1.png")],
        png3: [1, require("../../../assets/image2/videoAndSound/2-1.png")],
        png4: [1, require("../../../assets/image2/videoAndSound/7-1.png")],
        png5: [1, require("../../../assets/image2/videoAndSound/8-1.png")],
        png6: [1, require("../../../assets/image2/videoAndSound/9-1.png")],
        png7: [1, require("../../../assets/image2/videoAndSound/3-1.png")],
        png8: [0, require("../../../assets/image2/videoAndSound/10-0.png")],
        png9: [1, require("../../../assets/image2/videoAndSound/5-1.png")],
    },
    pause: {
        png0: [1, require("../../../assets/image2/videoAndSound/1-1.png")],
        png1: [0, require("../../../assets/image2/videoAndSound/6-0.png")],
        png2: [1, require("../../../assets/image2/videoAndSound/4-1.png")],
        png3: [1, require("../../../assets/image2/videoAndSound/2-1.png")],
        png4: [1, require("../../../assets/image2/videoAndSound/7-1.png")],
        png5: [1, require("../../../assets/image2/videoAndSound/8-2.png")],
        png6: [1, require("../../../assets/image2/videoAndSound/9-1.png")],
        png7: [1, require("../../../assets/image2/videoAndSound/3-1.png")],
        png8: [0, require("../../../assets/image2/videoAndSound/10-0.png")],
        png9: [1, require("../../../assets/image2/videoAndSound/5-1.png")],
    },
    infoImg: {
        normalQuestion: {
            png0_1: require("../../../assets/image2/dati/jszd.png"),
            png0_1_re: require("../../../assets/image2/dati/cxzd.png"),
            png1_1_obj: require("../../../assets/image2/dati/dtfx.png"),
            png1_1_sub: require("../../../assets/image2/dati/danr.png"),
            png2_1: require("../../../assets/image2/dati/dtxq.png"),
            png3_1: require("../../../assets/image2/dati/closetw.png"),
        },
        randomQuestion: {
            png0_0: require("../../../assets/image2/dati/cxsj-0.png"),
            png0_1: require("../../../assets/image2/dati/cxsj-1.png"),
            png1_0: require("../../../assets/image2/dati/dz-0.png"),
            png1_1: require("../../../assets/image2/dati/dz-1.png"),
            png2_0_obj: require("../../../assets/image2/dati/szda-0.png"),
            png2_1_obj: require("../../../assets/image2/dati/szda-1.png"),
            png2_0_sub_open: require("../../../assets/image2/dati/ckxsda-0.png"),
            png2_1_sub_open: require("../../../assets/image2/dati/ckxsda-1.png"),
            png2_1_sub_close: require("../../../assets/image2/dati/gbxsda.png"),
            png3_0: require("../../../assets/image2/dati/closesj_0.png"),
            png3_1: require("../../../assets/image2/dati/closesj.png"),
        },
        rushQuestion: {
            png0_0: require("../../../assets/image2/dati/cxqd-0.png"),
            png0_1: require("../../../assets/image2/dati/cxqd-1.png"),
            png1_0: require("../../../assets/image2/dati/dz-0.png"),
            png1_1: require("../../../assets/image2/dati/dz-1.png"),
            png2_0_obj: require("../../../assets/image2/dati/szda-0.png"),
            png2_1_obj: require("../../../assets/image2/dati/szda-1.png"),
            png2_0_sub_open: require("../../../assets/image2/dati/ckxsda-0.png"),
            png2_1_sub_open: require("../../../assets/image2/dati/ckxsda-1.png"),
            png2_1_sub_close: require("../../../assets/image2/dati/gbxsda.png"),
            png3_0: require("../../../assets/image2/dati/closeqd_0.png"),
            png3_1: require("../../../assets/image2/dati/closeqd.png"),
        },
    },
    moduleButton: {
        png0_0: require("../../../assets/image2/dati/tiwen1.png"),
        png0_1: require("../../../assets/image2/dati/tiwen2.png"),
        png1_0: require("../../../assets/image2/dati/suiji1.png"),
        png1_1: require("../../../assets/image2/dati/suiji2.png"),
        png2_0: require("../../../assets/image2/dati/qiangda1.png"),
        png2_1: require("../../../assets/image2/dati/qiangda2.png"),
    },
    questionOption: {
        png0_0: require("../../../assets/image2/questionOption/hudong_01.png"),
        png0_1: require("../../../assets/image2/questionOption/hudong_010.png"),
        png1_0: require("../../../assets/image2/questionOption/hudong_02.png"),
        png1_1: require("../../../assets/image2/questionOption/hudong_020.png"),
        png2_0: require("../../../assets/image2/questionOption/hudong_03.png"),
        png2_1: require("../../../assets/image2/questionOption/hudong_030.png"),
        png3_0: require("../../../assets/image2/questionOption/hudong_04.png"),
        png3_1: require("../../../assets/image2/questionOption/hudong_040.png"),
    },
};
